// Generated by CoffeeScript 2.5.1
var STANDARD_ELEMENTS, element, fragment, i, isString, len, name, prepareArrayChildren, prepareProps, pub, tags, wrap;

import React from 'react';

fragment = function(iterable) {
  return React.createElement(React.Fragment, {
    children: prepareArrayChildren(iterable)
  });
};

prepareArrayChildren = function(iterable) {
  var element, i, len, results;
  results = [];
  for (i = 0, len = iterable.length; i < len; i++) {
    element = iterable[i];
    if (React.isValidElement(element)) {
      results.push(element);
    } else {
      if (typeof element === 'function') {
        results.push(element());
      } else {
        console.log(element);
        results.push(console.error("What to do with the above element?"));
      }
    }
  }
  return results;
};

isString = function(object) {
  return (typeof object === 'string') || (object instanceof String);
};

prepareProps = function(object) {
  if (isString(object)) {
    return {
      children: object
    };
  } else if (Array.isArray(object)) {
    return {
      children: prepareArrayChildren(object)
    };
  } else {
    return object;
  }
};

element = function() {
  var component, props, second, third;
  switch (arguments.length) {
    case 1:
      component = arguments[0];
      return React.createElement(component);
    case 2:
      [component, second] = arguments;
      props = prepareProps(second);
      return React.createElement(component, props);
    case 3:
      [component, props, third] = arguments;
      if (Array.isArray(third)) {
        third = prepareArrayChildren(third);
      }
      props.children = third;
      return React.createElement(component, props);
    default:
      console.log(arguments);
      return console.error('What to do with the above arguments?');
  }
};

wrap = function(component) {
  return function(...args) {
    return element(component, ...args);
  };
};

STANDARD_ELEMENTS = ['a', 'abbr', 'address', 'area', 'article', 'aside', 'audio', 'b', 'base', 'bdi', 'bdo', 'big', 'blockquote', 'body', 'br', 'button', 'canvas', 'caption', 'cite', 'code', 'col', 'colgroup', 'data', 'datalist', 'dd', 'del', 'details', 'dfn', 'dialog', 'div', 'dl', 'dt', 'em', 'embed', 'fieldset', 'figcaption', 'figure', 'footer', 'form', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'head', 'header', 'hgroup', 'hr', 'html', 'i', 'iframe', 'img', 'input', 'ins', 'kbd', 'keygen', 'label', 'legend', 'li', 'link', 'main', 'map', 'mark', 'menu', 'menuitem', 'meta', 'meter', 'nav', 'noscript', 'object', 'ol', 'optgroup', 'option', 'output', 'p', 'param', 'picture', 'pre', 'progress', 'q', 'rp', 'rt', 'ruby', 's', 'samp', 'script', 'section', 'select', 'small', 'source', 'span', 'strong', 'style', 'sub', 'summary', 'sup', 'table', 'tbody', 'td', 'textarea', 'tfoot', 'th', 'thead', 'time', 'title', 'tr', 'track', 'u', 'ul', 'var', 'video', 'wbr'];

tags = {};

for (i = 0, len = STANDARD_ELEMENTS.length; i < len; i++) {
  name = STANDARD_ELEMENTS[i];
  tags[name] = wrap(name);
}

pub = {wrap, element, fragment, tags};

export {
  wrap,
  element,
  fragment,
  tags
};

export default pub;
